### ISSUE TITLE
Faraday::Error: :json is not registered on Faraday::Response

### ISSUE THREAD

**Issue by parabuzzle** [Agiley/Luminati#1]
While running through your example in the README, it seems there's a problem with the way you're using faraday

`connection      =   luminati.get_connection(country: nil, dns_resolution: nil, session: nil)`

```ruby
Faraday::Error: :json is not registered on Faraday::Response
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday.rb:189:in `lookup_middleware'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:203:in `use_symbol'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:96:in `response'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:99:in `block in build_connection'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday/connection.rb:91:in `initialize'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:97:in `build_connection'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:79:in `get_response'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:45:in `fetch_master_proxy'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:24:in `get_connection'
	from (irb):6
	from /opt/twitter/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

Using ruby-2.2.0

**Comment by parabuzzle** [comment]
Further investigation shows that json was removed from the newer version of faraday:

http://stackoverflow.com/questions/10654232/runtimeerror-json-is-not-registered-on-faradayrequest

I added `require 'faraday_middleware'`

but now I get:

```ruby
NoMethodError: undefined method `present?' for "invalid params":String
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:89:in `check_response_for_errors'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:83:in `get_response'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:45:in `fetch_master_proxy'
	from /opt/twitter/rvm/gems/ruby-2.2.0@niche/gems/luminati-0.0.2/lib/luminati/client.rb:24:in `get_connection'
	from (irb):8
	from /opt/twitter/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by Agiley** [comment]
Hey, glad that you're giving the gem a try :).

You are right, the json adapter apparently moved to faraday_middleware a while back. Due to not testing the gem in an isolated environment but rather testing it within a Rails app that included both Faraday/FardayMiddleware (was faster to do it that way when hacking together the gem) I didn't run into that issue. I've fixed it now though, as well as adding specs for testing the gem in an isolated environment.

Also, the error you received in terms of 'present?' means that you probably are not running the gem in an Rails environment. I've updated it to use !.empty? instead (which is the correct way).

Please give the new version 0.0.3 a try and report back if you still run into any issues:
gem 'luminati', '~> 0.0.3'
